name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  security_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Clone the repo on the machine
      uses: actions/checkout@v4

    - name: Use Node.js 21
      uses: actions/setup-node@v4
      with:
        node-version: 21
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install

    - name: Run npm security tests
      run: npm audit

  build_test:
    runs-on: ubuntu-latest
    needs: security_tests

    steps:
    - name: Clone the repo on the machine
      uses: actions/checkout@v4

    - name: Use Node.js 21
      uses: actions/setup-node@v4
      with:
        node-version: 21
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run integration tests
      run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
        - uses: actions/checkout@v3
        - uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.MY_RENDER_SERVICE_KEY }}
            api_key: ${{ secrets.MY_RENDER_API_KEY }}
            wait_deploy: true 